<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'An error occurred while installing Rights.' => 'Vyskytla se chyba se při instalaci Rights.',
  'Application authorization manager must extend the RDbAuthManager class.' => 'Authorization manager aplikace musí být poděděn od třídy RDbAuthManager.',
  'Application web user must extend the RWebUser class.' => 'Web user aplikace musí být poděděn od třídy RWebUser.',
  'Congratulations!' => 'Gratulujeme!',
  'Error' => 'Chyba',
  'Install Rights' => 'Instalovat Rights',
  'No' => 'Ne',
  'Notice: All your existing data will be lost.' => 'Upozornění: Veškerá vaše existující data budou ztracena.',
  'Please confirm if you wish to reinstall.' => 'Podvrďte prosím pokud si přejete reinstalovat Rights.',
  'Please try again or consult the documentation.' => 'Zkuste to prosím znovu nebo nahlédněte do dokumentace.',
  'Rights has been installed succesfully.' => 'Rights byl úspěšně nainstalován.',
  'Rights is already installed!' => 'Rights už je nainstalován!',
  'Yes' => 'Ano',
  'You can start by generating your authorization items' => 'Můžete začít vygenerováním vašich povolení',
  'You must be logged in to install Rights.' => 'Musíte být přihlášen, abyste mohl nainstalovat Rights.',
  'here' => 'zde',
);
