CREATE TABLE  `menu` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`label` VARCHAR( 50 ) NOT NULL ,
`url` VARCHAR( 50 ) NOT NULL ,
`position` INT NOT NULL ,
`menu` VARCHAR( 50 ) NOT NULL
) ENGINE = MYISAM ;